FROM node:22-alpine

ARG HTTP_PROXY
ARG HTTPS_PROXY
ARG NO_PROXY
ARG http_proxy
ARG https_proxy
ARG no_proxy

WORKDIR /app

COPY package.json package-lock.json ./
RUN npm ci

COPY . .

ENV VITE_FRONTEND_PORT=13002
EXPOSE 13002

CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0"]
